version: '3.0'

services:
  lite-server:
    image: node
    ports:
      - "3000-3002:3000" 
    volumes:
      - "./lite-server:/lite-server"
    entrypoint: ["/lite-server/init.sh", ""]
  json-server:
    image: node
    env_file:
      - json-server/test.env
    ports:
      - "3003-3005:3000" 
    volumes:
      - "./json-server:/json-server"
    entrypoint: ["/json-server/init.sh", ""]
  nginx:
    image: nginx
    ports:
      - "80:80"
    environment:
      - JSON_CONTAINER_IP=json-server
      - LITE_CONTAINER_IP=lite-server
    command: /bin/bash -c "envsubst < /etc/nginx/nginx.conf.template> /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    volumes:
      - "./nginx.conf.template:/etc/nginx/nginx.conf.template"  
      - "./templates:/etc/nginx/html"
    links:
      - json-server
      - lite-server
    